---

mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: foobar

mysql_db:
     - name: foo
       replicate: yes
     - name: bar
       replicate: no

mysql_users:
     - name: pangu
       pass: foobar
       priv: "*.*:ALL"

mysql_repl_user:
  - name: repl
    pass: foobar

mysql_repl_role: none
mysql_db_id: 7

mysql_service: mysqld

mysql_conf_dir: "/etc/"
