---
- name: install common components
  hosts: *
  sudo: yes
  roles:
    - common

- name: install zookeeper
  hosts: zookeeper_hosts
  sudo: yes
  roles:
    - { role: zookeeper, run_mode: 'Install' }
