---
- name: Remove conflicting mariadb package
  yum: name=mariadb-libs-5.5.47-1.el7_2.x86_64 state=removed

- name: Install the dependency package libselinux-python
  yum: name=libselinux-python state=installed

- name: Install the dependency packages MySQL-python
  yum: name=MySQL-python state=installed

- name: Copy rpm package to destination
  copy: src=x86_64/MySQL-server-5.6.30-1.el7.x86_64.rpm dest=/opt

- name: Install the MySQL server package
  yum: name=/opt/MySQL-server-5.6.30-1.el7.x86_64.rpm state=installed
